### PR TITLE
New swift version from scratch

### PR DESCRIPTION
**Pull request by ghost**
- New project written in Swift;
- Working audio streaming with open source framework;
- iOS, watchOS and macOS targets with minimum functionality;
- NEEDS DESIGN!

### CODE REVIEW

**Comment by Bevinsky** [comment]
Neat. Do you have a screenshot?

**Comment by ghost** [comment]
Yeah, take a look.
img_0913
img_0914
img_0915
img_0916
img_0917

**Comment by astra-bright** [comment]
i like it
i'd use it if i had an iDevice

**Comment by ameliaikeda** [comment]
You're a collaborator now~

**Pull request merged**
